### PR TITLE
Merging pong and user socket to avoid duplication

### PR DESCRIPTION
**Pull request by MaximePouce**
Matchmaking and challenges tested and work fine

Fixed the challenge being set as ranked
Fixed the game starting as 'over' when matchmaker create the same match-up a second time

### CODE REVIEW

**Comment by Scelewyn** [comment]
Please review and let me know if there is anything you'd like to see changed

**Review by znichola — APPROVED** [review]
looks pretty good have yet to test it though

**Comment by rnbw8** [comment]
I genuinely don't understand where my code went but since I trust you, all good on my side

**Review by rnbw8 — APPROVED** [review]
dont mind what i said before, find it, and all good!

**Pull request merged**
